//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHConfigurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generated
    {
        public long Index { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public string ParentName { get; set; }
        public bool IsButton { get; set; }
        public bool IsMenu { get; set; }
        public bool IsSeparator { get; set; }
        public bool IsGroup { get; set; }
        public string Image { get; set; }
        public string SuperTip { get; set; }
        public string ScreenTip { get; set; }
        public Nullable<long> TemplateNO { get; set; }
    }
}
