//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHConfigurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTime
    {
        public string RegionOrTT { get; set; }
        public bool TT { get; set; }
        public string OpenTime { get; set; }
        public string CloseTime { get; set; }
        public string Email { get; set; }
    }
}
