//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MassHelperEntities : DbContext
    {
        public MassHelperEntities()
            : base("name=MassHelperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Generated> Generateds { get; set; }
        public virtual DbSet<MailProperty> MailPropertys { get; set; }
        public virtual DbSet<MailsTemplate> MailsTemplates { get; set; }
        public virtual DbSet<WorkTime> WorkTimes { get; set; }
    }
}
